<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Jellyfin.Plugin.LookItUp</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.LookItUp</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.11">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="10.11.11">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

    <ItemGroup>
    <None Remove="Configuration\configPage.html" />
    <EmbeddedResource Include="Configuration\configPage.html" />
    <None Remove="Configuration\preparePage.html" />
    <EmbeddedResource Include="Configuration\preparePage.html" />
    <None Remove="Web\lookitup.js" />
    <EmbeddedResource Include="Web\lookitup.js" />
    <EmbeddedResource Include="Data\phrase-index.json.gz" />
    <None Remove="Data\phrase-index.json.gz" />
  </ItemGroup>

</Project>
